site_name: RADOA # サイトの名前
repo_url: https://github.com/RADOAProtocol/radoa_documents/
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  language: 'en'
  features:
    - navigation.tracking
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  logo: RADOA.jpeg

nav:
  - 'Home': index.md
  - 'Note':
    - '初めに': Note/index.md
    - 'マイコン': Note/micon.md
    - 'Mbed OS': Note/mbed_os.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  # Latex
  - pymdownx.arithmatex:
      generic: true

extra:
  search:
    language: 'en'

extra_css:
  # - stylesheets/extra.css
  # - stylesheets/dark_theme.css
  # - stylesheets/codehilite.css
  # Latex

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - include-markdown
  - search:
      lang: en
